### ISSUE TITLE
Disable automatic team balance and fix disabling auto-scramble

### ISSUE THREAD

**Issue by kraigher** [B3none/cs2-retakes#104]
I want to use your retake server to practice within my CS-team and we would like to choose our CT/T teams manually and not have the server switch people automatically. 

I am a C#-developer so I could make PR for such a feature if you are interested instead of me making a private fork.

# Proposal
- [ ] Add a `AutoTeamBalance` configuration option (default=`True`) that you can use to disable `TeamBalance()`
- [ ] Also it seems there is some kind of TeamBalance running in `CounterTerroristRoundWin` https://github.com/B3none/cs2-retakes/blob/master/RetakesPlugin/Modules/Managers/GameManager.cs#L140. This should also be disabled by `AutoTeamBalance`.
- [x] Fix `IsScrambleEnabled`. When reading the code I see that IsScrambleEnabled will not disable all calls to ScrambleTeams https://github.com/B3none/cs2-retakes/blob/master/RetakesPlugin/Modules/Managers/GameManager.cs#L79

**Comment by B3none** [comment]
This has been put behind a config in the latest update
