### ISSUE TITLE
how to turn off voice?

### ISSUE THREAD

**Issue by gRiHoNdAbRo** [B3none/cs2-retakes#11]
how to turn off voice side info?,  I couldn’t install the plugin for a long time until I manually renamed the folder
 cs2-retakes-master -> RetakesPlugin
now same problem with instadefuse and Instaplant, what am I doing wrong? thx.

**Comment by B3none** [comment]
It's a config to turn off the voice, set `EnableBombsiteAnnouncementVoices` to false
