### ISSUE TITLE
Allocators issue - not working 

### ISSUE THREAD

**Issue by walidhsn** [B3none/cs2-retakes#111]
hello guys i appreciate your hard work to build this plugins and my total respect for you ,so i tried the 3 allocators and nthg works : 
1 - Ravid's Allocator : i started the sqlserver and created a db configured the config file where i changed the host to localhost , and the username to root without password and i gave it the name of the db and then i lanched the sv and i enter nthg displayed .

2 - NokkviReyr's Allocator : the only one that is half working , just there s a bug where the changes after selecting are not affected  at all , nthg changes , and the database.json file that they are talking about doesn t even exist.

3 - Yoni's Allocator : this one is the most allocator that has stars , but it crashes the server idk why , after installing the plugin and launching the server ,it doesn't crash immediately but after i join to play i can't even pass the selection menu and the server is down. 

 > The readme files are poorly documented in the plugins except the cs2-retakes plugin.
 = > i hope there's a solution for one of this and i appreciate your help and support for the cs2 community server.
note: this s my first time starting a cs 2 server, i made it as a challenge for my self to learn ,so i m not fully informative about all the aspects ,i can be wrong or missing some configuration in them idk, i hosted the server on an Azure VM , using Windows base system , with WindowsGSM and cs2 plugin i managed to install the server and i configured it, then installed the metamod and counterstikesharp, after that i installed the plugins one by one as the guide in the readmefile, the retake plugin works fine except the weapons allocator, for example in  NokkviReyr's Allocator, it says pistol round and the player still having rifle in his hands.

**Comment by emantrigo** [comment]
I can only help with yoni's . If you are using a windows server you need to change this line : 
`"EnableCanAcquireHook": false,`

**Comment by walidhsn** [comment]
hello thx for the reply where can i find that line ?

**Comment by B3none** [comment]
That's in the config file for the allocator, as this is not a Retakes plugin issue I'm going to close this issue.
