### ISSUE TITLE
Not receiving weapons.

### ISSUE THREAD

**Issue by pixeelff** [B3none/cs2-retakes#116]
Players are not receiving weapons after last CS update. I tried without allocator and with 2 plugins that allocate weapons.

**Comment by B3none** [comment]
Which allocator are you using?

**Comment by pixeelff** [comment]
KPSAllocator, but as I said even the built-in allocator doesn't work

**Comment by B3none** [comment]
Make sure you update your counter strike sharp to the latest version

**Comment by pixeelff** [comment]
I tried updating the cssharp, i tried even reinstalling the whole server, nothing worked. I tried without multiple plugins such as weapon paints and even tried with only the retake plugin, nothing succeeded.

**Comment by B3none** [comment]
I've tested it and it's working as expected
