### ISSUE TITLE
CS2 Crashes after reconnection

### ISSUE THREAD

**Issue by ezz3r** [B3none/cs2-retakes#118]
I just removed all my plugins and tested it only with cs2-retakes plugin.
If the round started and you disconnect and then reconnect the game crashes.

It only happens when you are in a round defending/attacking. 
If its warmup it does not crash after reconnecting

I also tested it with my friend, it also happens to him :/

Client: Windows 11
Server: Linux

**Comment by mrc4tt** [comment]
What CSS version are you using?

**Comment by ezz3r** [comment]
v215 with runtime linux build
Let me test it with v217 r quick

**Comment by ezz3r** [comment]
No more crashes with v217 👍
