### ISSUE TITLE
Game crash IsAutoPlantEnabled

### ISSUE THREAD

**Issue by MouradHasnaoui** [B3none/cs2-retakes#128]
Hey,
Just a heads-up about an issue after yesterday's update. The game crashes right at the start of a round if "IsAutoPlantEnabled" is set to true. Changing it to false fixes the problem.

**Comment by ipsvn** [comment]
This is fixed in #127, wait for it to be merged

**Comment by csbob1337** [comment]
still crashing for me :/

**Comment by ipsvn** [comment]
> still crashing for me :/

Running latest version of the plugin? and the same crash as before where its right after autoplant happens?
