### ISSUE TITLE
[Question] How do I turn down the volume of the bomb site indicator voices?

### ISSUE THREAD

**Issue by Vichoko** [B3none/cs2-retakes#130]
The voices that indicates the bomb site, e.g. saying "Bomb site alpha" sounds too loud on some setups. Is there any way to turn it down?

**Comment by B3none** [comment]
It’s client side so it’s not something you’re able to change unfortunately

**Comment by andersontvcs2** [comment]
Hi there, 

Is there anyway to disable the voices?

**Comment by B3none** [comment]
It’s a setting in the config

**Comment by andersontvcs2** [comment]
Thank you,
