### ISSUE TITLE
dust2 spawns broke in last update

### ISSUE THREAD

**Issue by LukaLiuzzi** [B3none/cs2-retakes#131]
Dust2 spawns were broken in the last update due to map changes.
It happened to me that in some rounds the c4 appears planted in TT or CT, the curious thing is that if I put /showspawns, no spawns appear in those areas

**Comment by B3none** [comment]
I suspect you've got too many players in your server compared to the possible spawns. Each of the players start in their respective spawns and are then teleported to the retakes spawns prior to round start.
