### ISSUE TITLE
Can you change the announcement color by replacing purple with blue?

### ISSUE THREAD

**Issue by NikolaJyun** [B3none/cs2-retakes#133]
"retakes.bombsite.announcement": "Retake [GREEN]{0}[NORMAL]: [LIGHT_RED]{1} Ts[NORMAL] vs [PURPLE]{2} CTs",
 
 to
 
  "retakes.bombsite.announcement": "Retake [GREEN]{0}[NORMAL]: [LIGHT_RED]{1} Ts[NORMAL] vs [BLUE]{2} CTs",

**Comment by B3none** [comment]
Post a pull request with the change along with screenshots of how it looks in game, and if I agree it looks better then we can merge the PR. The reason I went for purple is because that’s what the original retakes implementation had.

**Comment by NikolaJyun** [comment]
I'm sorry, but I don't really know how to use the GitHub PR feature. I also don't have a coding background. I tried directly changing the color code to BLUE in the lang file, but it didn't work. I hope it can be one of the three blue colors shown in the image.

![image](https://github.com/user-attachments/assets/fec2b3ec-3772-4f6b-921d-08c10d61c8b4)

Source:https://github.com/oqyh/cs2-Vote-GoldKingZ

**Comment by B3none** [comment]
As this is a per server implementation, I'm going to close this ticket.
