### ISSUE TITLE
Message color support

### ISSUE THREAD

**Issue by Kakkuh** [B3none/cs2-retakes#138]
I tried using "default" colors (image below), but for some reason they don't work. For example [GOLD] is just white. Is there a way to use these colors or is it not supported?
![352485476-fec2b3ec-3772-4f6b-921](https://github.com/user-attachments/assets/be1d82ea-60a4-4517-a94f-8ed5ee5828e8)

**Comment by B3none** [comment]
https://github.com/B3none/cs2-retakes/blob/49a48326e23a24e934d378fca5212bca8c645d63/RetakesPlugin/Modules/Translator.cs#L51

**Comment by Kakkuh** [comment]
I did a bit more testing and it seems like the problem is only in the prefix. Translation works in normal messages, but not in "retakes.prefix"
I sent an image below and here's what it looks like in the lang file
`"retakes.prefix": "[ORANGE]test [GREEN]» "`
`"retakes.bombsite.announcement": "Retake [GREEN]{0}[NORMAL]: [LIGHT_RED]{1} Ts[NORMAL] vs [ORANGE]{2} CTs"`

![image](https://github.com/user-attachments/assets/9d7e06b0-c81f-4780-8515-129e4c214790)

**Comment by B3none** [comment]
Can you try adding a space before the prefix colour

**Comment by Kakkuh** [comment]
Tested and it fixed the problem, thanks! :D

**Comment by Kakkuh** [comment]
Tested and it fixed the problem, thanks! :D
