### ISSUE TITLE
The round doesn't end when the last CT player leaves.

### ISSUE THREAD

**Issue by NikolaJyun** [B3none/cs2-retakes#140]
during a match, if the last CT player leaves or moves to spectator, the round doesn't end immediately but waits for the C4 to explode before ending.

**Comment by B3none** [comment]
I checked the code, and this should be happening. When a player disconnects this code is run:
https://github.com/B3none/cs2-retakes/blob/master/RetakesPlugin/Modules/Helpers.cs#L205

**Comment by NikolaJyun** [comment]
@B3none I'll pay more attention while playing because I remember a few instances where the round didn't end immediately. Maybe it's because AFK Manager moved the AFK players to spectator mode, which didn't trigger the condition.

**Comment by B3none** [comment]
Trying to get this plugin to play nice with the AFK manager is an up hill battle unfortunately

**Comment by NikolaJyun** [comment]
It really doesn't work.

https://discord.com/channels/@me/1278066000440328252/1279171291487928331

https://cdn.discordapp.com/attachments/1278066000440328252/1279171286660022293/Counter-strike_2_2024.08.31_-_03.58.49.12.mp4?
ex=66d572d8&is=66d42158&hm=39d6f62c42b07681499e247d6add2b01eb7d22a04b759ee834fe270032b4d003&
