### ISSUE TITLE
[REQ] Retakes queue priority for VIP players

### ISSUE THREAD

**Issue by crashzk** [B3none/cs2-retakes#3]
Can we expect a separate plugin or along with the retake of the VIP Queue version?

https://github.com/B3none/csgo-retakes-vip-queue

**Comment by B3none** [comment]
I think the best approach would be implementing it into this plugin, potentially declaring priority in the config. I'm adding a retakes config file as we speak.

**Comment by B3none** [comment]
> I think the best approach would be implementing it into this plugin, potentially declaring priority in the config. I'm adding a retakes config file as we speak.

Ok, so the retakes config was released, we could implement queue priority but I need to decide how I want the config for it to look.
