### ISSUE TITLE
Process terminated

### ISSUE THREAD

**Issue by juandrep** [B3none/cs2-retakes#31]
Still got this error after some time of play on the server:

Process terminated. A callback was made on a garbage collected delegate of type 'System.Private.CoreLib!System.Action::Invoke'.

**Comment by B3none** [comment]
Hmm, I wonder if it's a memory leak. Can you send over a list of the plugins you're using? Could you also try rolling back to one of the older versions of Retakes and see if the crashing issue goes away? It'll help confirm whether or not it's the retakes plugin causing the issue or one of your other plugins.

**Comment by juandrep** [comment]
Where the list of plugins i'm using on the server:

css_plugins list
  List of all plugins currently loaded by CounterStrikeSharp: 9 plugins loaded.
  [#1:LOADED]: "ResetScore" (1.0.5) by StefanX
  [#2:LOADED]: "Retakes Allocator Plugin" (1.1.0)
  [#3:LOADED]: "SteamGroupRestrict" (1.0.0) by BMathers
  [#4:LOADED]: "WeaponPaints" (1.3h) by Nereziel & daffyy
    Skin and knife selector, standalone and web-based
  [#5:LOADED]: "CallAdmin" (1.6.1) by 1MaaaaaacK
    Report System with database support
  [#6:LOADED]: "CS2InstantDefuse" (1.2.0) by LordFetznschaedl
    Simple Plugin that allowes the bomb to be instantly defused when no enemy is alive (configurable) and no utility is in use (configurable)
  [#7:LOADED]: "Retakes Plugin" (1.3.2) by B3none
    Community retakes for CS2.
  [#8:LOADED]: "[RanksPoints]" (2.0.6) by ABKAM
  [#9:LOADED]: "CS2-Tags" (1.0.3a) by daffyy
    Add player tags easily in cs2 game

**Comment by B3none** [comment]
> Where the list of plugins i'm using on the server:
> 
> css_plugins list List of all plugins currently loaded by CounterStrikeSharp: 9 plugins loaded. [#1:LOADED]: "ResetScore" (1.0.5) by StefanX [#2:LOADED]: "Retakes Allocator Plugin" (1.1.0) [#3:LOADED]: "SteamGroupRestrict" (1.0.0) by BMathers [#4:LOADED]: "WeaponPaints" (1.3h) by Nereziel & daffyy Skin and knife selector, standalone and web-based [#5:LOADED]: "CallAdmin" (1.6.1) by 1MaaaaaacK Report System with database support [#6:LOADED]: "CS2InstantDefuse" (1.2.0) by LordFetznschaedl Simple Plugin that allowes the bomb to be instantly defused when no enemy is alive (configurable) and no utility is in use (configurable) [#7:LOADED]: "Retakes Plugin" (1.3.2) by B3none Community retakes for CS2. [#8:LOADED]: "[RanksPoints]" (2.0.6) by ABKAM [#9:LOADED]: "CS2-Tags" (1.0.3a) by daffyy Add player tags easily in cs2 game

Be sure to use the latest release so we’re looking at the same code.

I’d also recommend using the instant defuse in the readme instead

**Comment by juandrep** [comment]
Is the latest version of the retakes and the insta defuse is the one from you

We have tryed put the rest of the plugins on disable folder and the error appears only with the insta defuse and the retakes

**Comment by B3none** [comment]
@juandrep PM me on discord and we can run through it together

**Comment by B3none** [comment]
We've done extensive testing and ruled this plugin out as the reason for your crashes.
