### ISSUE TITLE
Change name of Portuguese translation file

### ISSUE THREAD

**Issue by crashzk** [B3none/cs2-retakes#33]
I believe you need to change to pt-BR and pt-PT.

- `pt-BR` = For Brazilian Portuguese translations
- `pt-PT` = For Portuguese translations from Portugal

From what I understand they are keeping everything in one format: https://learn.microsoft.com/en-us/bingmaps/rest-services/common-parameters-and-types/supported-culture-codes

**Comment by B3none** [comment]
Send a PR with these changes and I will accept them, but I have been on servers running in Portuguese. Make sure your server lang is set to `pt`

**Comment by crashzk** [comment]
> Send a PR with these changes and I will accept them, but I have been on servers running in Portuguese. Make sure your server lang is set to `pt`

Yes, if I put `pt` on the server it works. The question would be the writing itself, Portuguese from Portugal would be very different from Portuguese from Brazil.

With this I can translate the sentences into Brazilian Portuguese, but some user from Portugal can replace it back to the way they write in this case.

Hence the need for two translation files, one for each country, let's say. I will be doing the PR in any case as soon as possible so you can check.
