### ISSUE TITLE
Vip queue seems like not working correctly

### ISSUE THREAD

**Issue by st1ng2** [B3none/cs2-retakes#43]
I have root flag, but can't join to the game

css_debugqueues shows this. No error in logs
```
[Retakes 1.3.10] ActivePlayers (BEFORE): OXYSKY, bum11, NaikoN, A, magic, SHram666, PYREX, ✪Juzeppe[M1GHTY], Jyzer
[Retakes 1.3.10] QueuePlayers (BEFORE): st1ng, Kyoto, habi卍
[Retakes 1.3.10] _roundTerrorists (BEFORE): st1ng, magic, SHram666, PYREX, bum11
[Retakes 1.3.10] _roundCounterTerrorists (BEFORE): OXYSKY, Kyoto, NaikoN, ✪Juzeppe[M1GHTY], habi卍, A, Jyzer
```
 
And sometimes player who joined first are moving to spec randomly, without putting vips to the game. There is no vips other than me

config
```
{
  "Version": 4,
  "MaxPlayers": 9,
  "TerroristRatio": 0.45,
  "RoundsToScramble": 4,
  "IsScrambleEnabled": true,
  "EnableFallbackAllocation": false,
  "EnableBombsiteAnnouncementVoices": false,
  "EnableBombsiteAnnouncementCenter": true,
  "ShouldBreakBreakables": true,
  "ShouldOpenDoors": false
}
```

**Comment by JesseMH** [comment]
I have the same issue, VIPs aren't given priority, neither is `@css/root` or `#css/admin` with the vip flag set. 
Expected: Anyone with the `@css/vip` flag is put into a game and a non-vip player is moved to spec.
Actual: All users treated the same.

**Comment by B3none** [comment]
I have an updated version in a PR if you want to test it? @JesseMH
