### ISSUE TITLE
Bombsite checking not working

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [B3none/cs2-retakes#45]
Bombsite checking not working. Stand inside red lines, and it will not always make a bomb planter spawn, even tho it should.

**Comment by B3none** [comment]
I've updated the `addspawn` command to handle this now, I'm not sure why getting the property `player.PlayerPawn.Value.InBombZone` is always returning false.

**Comment by B3none** [comment]
Posted an issue on the CounterStrikeSharp repository: https://github.com/roflmuffin/CounterStrikeSharp/issues/295

**Comment by B3none** [comment]
Fixed in https://github.com/B3none/cs2-retakes/releases/tag/1.3.24
