### ISSUE TITLE
[BUG] Removing the knives from the players

### ISSUE THREAD

**Issue by crashzk** [B3none/cs2-retakes#48]
Whenever the round starts, players are left without a knife, even if it is the default in CS2.

Players are only spawning with Primary and Secondary Weapons, knives never come to players.

**Comment by B3none** [comment]
Are you using the fallback allocator?

Are using a weapon skins plugin?

**Comment by evenbreak** [comment]
> Are you using the fallback allocator?
> 
> Are using a weapon skins plugin?

Im having the same issue, but only if i use weapon skin, do u know any way to fix it? or its not possible yet

thanks in advance

**Comment by crashzk** [comment]
> Are you using the fallback allocator?
> 
No, using the retake itself so far.

> Are using a weapon skins plugin?
> 
Yes, I'm using [Weapon Paints](https://github.com/Nereziel/cs2-WeaponPaints).

**Comment by crashzk** [comment]
The solution above worked.
