### ISSUE TITLE
[REQ] Add MessagePrefix in translations

### ISSUE THREAD

**Issue by crashzk** [B3none/cs2-retakes#54]
Would it be possible to add the `MessagePrefix` to the translations?

https://github.com/B3none/cs2-retakes/blob/11c5655d29cb43defc2c9f12c06426fcb2ef62f5/RetakesPlugin.cs#L31

I ask because I would like to change the colour of the message, or do you have no intention of implementing this feature at the moment?

**Comment by B3none** [comment]
This change is in the latest release
