### ISSUE TITLE
[REQ] Fast Defuse

### ISSUE THREAD

**Issue by Sh1su** [B3none/cs2-retakes#56]
Hello B3none,

I think your retake plugin is very well done. But there is one improvement I would like to see. If I want to detonate all CT's after a short time, i.e. when the 5 second music timer has not yet started, it would be nice if I could detonate the bomb directly and not have to wait 5 or 10 seconds. Would an implementation be possible?

Kind regards
Sh1su

**Comment by B3none** [comment]
@Sh1su yes, this is possible. Can you post this as a request on https://github.com/b3none/cs2-instadefuse

**Comment by Sh1su** [comment]
@B3none 

Thanks for the quick reply, that's exactly what I was looking for.
