### ISSUE TITLE
Buy Menu Inside Server

### ISSUE THREAD

**Issue by evenbreak** [B3none/cs2-retakes#57]
So well, i tried to use all the 3 plugins u mentioned but i have some problems, the main problem is, i want be able to buy using buy menu which is more convinent, it would be great to disable the commands !gun !guns(have a command for that or just toggle)

or just use the buy menu so it wont interfier with !gun !guns (since it wont work as i want, i cant buy m4a4 if i have m4a1s selected for example, kelver and helmet t side isnt showing, u have to buy it, and sometimes u start the round without anything(gun, knife, everything), you gotta buy it before it starts

![2024-01-24_23-23-20](https://github.com/B3none/cs2-retakes/assets/149022728/7bad048c-ce5d-4fda-aa33-5918447a1e6a)
 which you can see here

this only happens if i have the b menu activated by using , if i disable mp_buy_anywhere it goes back to normal

mp_buy_anywhere 1
mp_buytime 10
mp_maxmoney 65535
mp_startmoney 65535
mp_afterroundmoney 65535

**Comment by evenbreak** [comment]
also, idk if this problem is with cs2 retake or cs2 allocatorhttps://github.com/yonilerner/cs2-retakes-allocator <<

**Comment by B3none** [comment]
This is a request for the implemented of your retakes allocator. Closing this.
