### ISSUE TITLE
Separate hint and chat bombsite announce.

### ISSUE THREAD

**Issue by IT-CHI** [B3none/cs2-retakes#69]
separate please hint & chat message because it will not get drawn in hint and breakdown since hints has html formatting
config:"retakes.bombsite.announcement": "Retake [GREEN]{0}[SILVER]: [RED]{1} Ts[SILVER] vs [BLUE]{2} CTs"
result:
![obrazek](https://github.com/B3none/cs2-retakes/assets/56051031/16905669-3870-44a4-a67f-fd6c7a8d1bd6)
![obrazek](https://github.com/B3none/cs2-retakes/assets/56051031/abf63730-06d4-4db4-a94c-67515f4243d5)

**Comment by B3none** [comment]
Ah yes, I will need to update the translation later to handle that

**Comment by B3none** [comment]
Had a quick look into this and it's not initially as easy as "just implementing a new translation", the translation wrapper will need to be updated to handle HTML tags too for the supported colours. I have thought of a solution to implement it which would be to switch `[GREEN]` for `<font color="green">` and keep a count of the total replaced then prepend the translation string with `</font>` for the total number of replacements. This might want some regex magic to do this but it's going to take longer than 5 minutes to implement 👍

**Comment by B3none** [comment]
This issue is fixed in the `1.3.26` release 👍
