### ISSUE TITLE
Linux OS Support

### ISSUE THREAD

**Issue by pimpmyname3** [B3none/cs2-retakes#7]
Hey,
I'm curious if there are plans for Linux OS support in the near future? :)

**Comment by B3none** [comment]
@pimpmyname3 there are already people running it on Linux, what’s your issue?

**Comment by pimpmyname3** [comment]
Sorry, i thought counterstrikesharp didnt have a dotnet build integrated in linux, i have added "counterstrikesharp-with-runtime-build-142" and your plugin works like a charm :) closing
