### ISSUE TITLE
Compatibility with WeaponPaints

### ISSUE THREAD

**Issue by johandrevwyk** [B3none/cs2-retakes#72]
When using Retakes and WeaponPaints simultaneously, the retakes allocator overrides the knife given by WeaponPaints, could there possibly be a config setting to not allocate the knife at all?

**Comment by daffyyyy** [comment]
Wp give a knife on player spawn, but retake remove all weapons :/ + small delay

**Comment by B3none** [comment]
Pretty sure I tried this before and there was a bug where no knife was allocated whatsoever

**Comment by daffyyyy** [comment]
For giving knife u dont need a delay

**Comment by LinusFromArox** [comment]
this would be  a handy fix

**Comment by RoyZ-iwnl** [comment]
This will cause a Segmentation fault.😢Any idea for fixing?

**Comment by st1ng2** [comment]
still relevant

**Comment by B3none** [comment]
If @daffyyyy or anyone from the weapon paints plugin team wants to make a PR to fix compatibility with their plugin, I am happy to accept a PR.

**Comment by everkk** [comment]
We need this fix

**Comment by B3none** [comment]
This should be fixed with `1.4.0` 👍 You will also need to update your allocator to `>= 1.4.1` of @yonilerner's allocator
