### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by notvichh** [B3none/cs2-retakes#89]
After installing the plugin, the server simply cannot turn on

**Comment by B3none** [comment]
What version of css / metamod / retakes are you using?

**Comment by notvichh** [comment]
1.4.1 latest version. I threw everything in as in the instructions and just crashed

**Comment by B3none** [comment]
@notvichh ping me on discord and I'll run through it with you 👍

**Comment by B3none** [comment]
It's hard to tell but I think I've fixed this with the `1.4.2` release.
