### ISSUE TITLE
Map config data null error

### ISSUE THREAD

**Issue by pimpmyname2** [B3none/cs2-retakes#92]
Hello,
I think after updating counterstrikesharp to v201 this error started happening:
![image](https://github.com/B3none/cs2-retakes/assets/79339372/920fcaf1-d682-4ab2-94a1-0fc7d6223fb9)

Map configs are generated, all other plugins doesnt have any errors.
meta version & css_plugins list output:
![image](https://github.com/B3none/cs2-retakes/assets/79339372/87602f2a-dd1b-4129-a133-a0ed8ea279b7)

Our retake server is currently unplayable because the round keeps restarting
![image](https://github.com/B3none/cs2-retakes/assets/79339372/f39c8762-6aab-4e91-b62b-058569af95a8)

**Comment by B3none** [comment]
Give this a try alongside the latest version of CounterStrikeSharp: https://github.com/B3none/cs2-retakes/releases/tag/2.0.0

**Comment by pimpmyname2** [comment]
Okay, thanks. Gj :)
