### ISSUE TITLE
retakes_config.json Not generated

### ISSUE THREAD

**Issue by bSchutters** [B3none/cs2-retakes#93]
Hello, I cant changes settings options because the file retakes_config.json are not generated

**Comment by B3none** [comment]
Can you confirm what CSS version you’re using? I think there might be an issue with json parsing for CSS version 201 for some reason

**Comment by bSchutters** [comment]
Listing 1 plugin: [01] CounterStrikeSharp (v201 @ e4d598d) by Roflmuffin

I've another error in my vps console: 

01:15:44 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.Exception: Map config data is null

**Comment by B3none** [comment]
Ok, so dotnet 8 wasn't working correctly with v201 for Retakes `1.4.2` here's the latest release which should fix your problem:
https://github.com/B3none/cs2-retakes/releases/tag/2.0.0

**Comment by B3none** [comment]
Others have confirmed this is working. Closing 👍
