### ISSUE TITLE
Retakes not working with lastest version of Csharp 202

### ISSUE THREAD

**Issue by MickaNoob** [B3none/cs2-retakes#95]
Retakes not working with lastest version of Csharp 202

**Comment by B3none** [comment]
Test it using the latest code I just merged, I’ll make a release for it shortly

**Comment by B3none** [comment]
Try this: https://github.com/B3none/cs2-retakes/releases/tag/2.0.0 and let me know how you get on 👍

**Comment by Porcellacion** [comment]
Also having issues installing this on CSS v202 linux runtime.

```
Mar 26 10:43:15:  css_plugins list
Mar 26 10:43:15:    List of all plugins currently loaded by CounterStrikeSharp: 2 plugins loaded.
Mar 26 10:43:15:    [#1:UNREGISTERED]: "Unknown" (Unknown)
Mar 26 10:43:15:    [#2:UNREGISTERED]: "Unknown" (Unknown)
```

These 2 plugins are "RetakesPlugin" & "RetakesPluginShared"

**Comment by B3none** [comment]
Others have confirmed this is working. Try installing it again and see if the issue persists. Closing this issue now 👍

**Comment by MickaNoob** [comment]
Hi, yeah it's working thx for the fix. I found a new problem, i create a new issue. (not important)
