### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by notvichh** [B3none/cs2-retakes#98]
I just installed this plugin, everything is as it should, it starts for the first time, but after restarting the server crashes. CSS 201 Meta 1282
or did I not download something?

**Comment by B3none** [comment]
Can you confirm what versions of the shared plugin, and allocator plugin you are using?

**Comment by notvichh** [comment]
> Можете ли вы подтвердить, какие версии общего плагина и плагина распределителя вы используете?

2.0.0 retake
2.0.0 shared
cs2-retakes-allocator 2.0.0 alpha

**Comment by B3none** [comment]
This should be fixed in the latest version, if you have any issues reopen this issue with a crash dump / some logs 👍
